using Verifier = FlashOWare.Tests.CodeAnalysis.CSharp.Testing.CSharpIncrementalGeneratorVerifier<FlashOWare.Generators.Enumerations.EnumIsDefinedGenerator>;

namespace FlashOWare.Tests.Generators.Enumerations;

public class EnumIsDefinedGeneratorTests
{
	[Fact]
	public async Task Execute_NoAttributes_NoEmit()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			public class Class
			{
				public void Method()
				{
					_ = Enum.IsDefined(DateTimeKind.Utc);
				}
			}
			""";

		await Verifier.VerifyAsync(code);
	}

	[Fact]
	public async Task Execute_WithAttribute_AddSource()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumIsDefinedAttribute<DateTimeKind>]
			public static partial class Class
			{
			}
			""";

		string generated = $$"""
			{{AutoGenerated.Header}}
			namespace Namespace;

			partial class Class
			{
				{{AutoGenerated.GeneratedCodeAttribute}}
				public static bool IsDefined(global::System.DateTimeKind value)
				{
					return value is
						global::System.DateTimeKind.Unspecified or
						global::System.DateTimeKind.Utc or
						global::System.DateTimeKind.Local;
				}
			}

			""";

		await Verifier.VerifyAsync(code, ("Namespace.Class.IsDefined.g.cs", generated));
	}

	[Fact]
	public async Task Execute_WithAttributes_AddSources()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumIsDefinedAttribute<DateTimeKind>]
			public static partial class Class
			{
			}

			[GeneratedEnumIsDefinedAttribute<DateTimeKind>]
			public partial class NotStatic
			{
			}

			[{|#0:GeneratedEnumIsDefinedAttribute<DateTimeKind>|}]
			public partial struct ValueType
			{
			}
			""";

		DiagnosticResult diagnostic = Diagnostic.CS0592(0, "GeneratedEnumIsDefinedAttribute<>", "class");

		(string, string)[] generated = [
			("Namespace.Class.IsDefined.g.cs", $$"""
				{{AutoGenerated.Header}}
				namespace Namespace;

				partial class Class
				{
					{{AutoGenerated.GeneratedCodeAttribute}}
					public static bool IsDefined(global::System.DateTimeKind value)
					{
						return value is
							global::System.DateTimeKind.Unspecified or
							global::System.DateTimeKind.Utc or
							global::System.DateTimeKind.Local;
					}
				}

				"""),
			("Namespace.NotStatic.IsDefined.g.cs", $$"""
				{{AutoGenerated.Header}}
				namespace Namespace;

				partial class NotStatic
				{
					{{AutoGenerated.GeneratedCodeAttribute}}
					public static bool IsDefined(global::System.DateTimeKind value)
					{
						return value is
							global::System.DateTimeKind.Unspecified or
							global::System.DateTimeKind.Utc or
							global::System.DateTimeKind.Local;
					}
				}

				""")
		];

		await Verifier.VerifyAsync(code, diagnostic, generated);
	}

	[Fact]
	public async Task Execute_Partial_AddSource()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumIsDefinedAttribute<DateTimeKind>]
			public static partial class Class
			{
			}

			[GeneratedEnumIsDefinedAttribute<UriKind>]
			public static partial class Class
			{
			}

			[GeneratedEnumIsDefinedAttribute<DateTimeKind>]
			[GeneratedEnumIsDefinedAttribute<UriKind>]
			public static class NotPartial
			{
			}
			""";

		string generated = $$"""
			{{AutoGenerated.Header}}
			namespace Namespace;

			partial class Class
			{
				{{AutoGenerated.GeneratedCodeAttribute}}
				public static bool IsDefined(global::System.DateTimeKind value)
				{
					return value is
						global::System.DateTimeKind.Unspecified or
						global::System.DateTimeKind.Utc or
						global::System.DateTimeKind.Local;
				}

				{{AutoGenerated.GeneratedCodeAttribute}}
				public static bool IsDefined(global::System.UriKind value)
				{
					return value is
						global::System.UriKind.RelativeOrAbsolute or
						global::System.UriKind.Absolute or
						global::System.UriKind.Relative;
				}
			}

			""";

		await Verifier.VerifyAsync(code, ("Namespace.Class.IsDefined.g.cs", generated));
	}

	[Fact]
	public async Task Execute_GlobalNamespace_AddSource()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			[GeneratedEnumIsDefinedAttribute<DateTimeKind>]
			public static partial class Class
			{
			}
			""";

		string generated = $$"""
			{{AutoGenerated.Header}}
			partial class Class
			{
				{{AutoGenerated.GeneratedCodeAttribute}}
				public static bool IsDefined(global::System.DateTimeKind value)
				{
					return value is
						global::System.DateTimeKind.Unspecified or
						global::System.DateTimeKind.Utc or
						global::System.DateTimeKind.Local;
				}
			}

			""";

		await Verifier.VerifyAsync(code, ("Class.IsDefined.g.cs", generated));
	}

	[Fact]
	public async Task Execute_ErrorType_NoEmit()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumIsDefinedAttribute<{|#0:Error|}>]
			[GeneratedEnumIsDefinedAttribute<{|#1:true|}>]
			[GeneratedEnumIsDefinedAttribute<{|#2:240|}>]
			[{|#3:GeneratedEnumIsDefinedAttribute<>|}]
			[GeneratedEnumIsDefinedAttribute<{|#4:]|}
			public static partial class Class
			{
			}
			""";

		DiagnosticResult[] diagnostics = [
			Diagnostic.CS0246(0, "Error"),
			Diagnostic.CS1031(1),
			Diagnostic.CS1031(2),
			Diagnostic.CS7003(3),
			Diagnostic.CS1003(4, '>'),
			Diagnostic.CS1031(4),
		];

		await Verifier.VerifyAsync(code, diagnostics);
	}

	[Fact]
	public async Task Execute_IncludeErrors_AddSource()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumIsDefinedAttribute<DateTimeKind>]
			[GeneratedEnumIsDefinedAttribute<{|#0:?|}>]
			public static partial class Class
			{
			}

			[{|#1:GeneratedEnumIsDefinedAttribute<DateTimeKind, DateTimeKind>|}]
			[{|#2:GeneratedEnumIsDefinedAttribute<,>|}]
			[{|#3:GeneratedEnumIsDefinedAttribute|#3}{|#4:>|#4}]
			[{|#5:GeneratedEnumIsDefinedAttribute|}]
			public static partial class Class
			{
			}
			""";

		DiagnosticResult[] diagnostics = [
			Diagnostic.CS1031(0),
			Diagnostic.CS0305(1, "type", "GeneratedEnumIsDefinedAttribute<TEnum>", 1),
			Diagnostic.CS0305(2, "type", "GeneratedEnumIsDefinedAttribute<TEnum>", 1),
			Diagnostic.CS0305(3, "type", "GeneratedEnumIsDefinedAttribute<TEnum>", 1),
			Diagnostic.CS1001(4),
			Diagnostic.CS0305(5, "type", "GeneratedEnumIsDefinedAttribute<TEnum>", 1),
		];

		string generated = $$"""
			{{AutoGenerated.Header}}
			namespace Namespace;

			partial class Class
			{
				{{AutoGenerated.GeneratedCodeAttribute}}
				public static bool IsDefined(global::System.DateTimeKind value)
				{
					return value is
						global::System.DateTimeKind.Unspecified or
						global::System.DateTimeKind.Utc or
						global::System.DateTimeKind.Local;
				}
			}
		
			""";

		await Verifier.VerifyAsync(code, diagnostics, ("Namespace.Class.IsDefined.g.cs", generated));
	}
}
