using Verifier = FlashOWare.Tests.CodeAnalysis.CSharp.Testing.CSharpIncrementalGeneratorVerifier<FlashOWare.Generators.Enumerations.EnumGetNameGenerator>;

namespace FlashOWare.Tests.Generators.Enumerations;

public class EnumGetNameGeneratorTests
{
	[Fact]
	public async Task Execute_NoAttributes_NoEmit()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			public class Class
			{
				public void Method()
				{
					_ = Enum.GetName(DateTimeKind.Utc);
				}
			}
			""";

		await Verifier.VerifyAsync(code);
	}

	[Fact]
	public async Task Execute_WithAttributes_AddSource()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumGetNameAttribute<DateTimeKind>]
			public static partial class Class
			{
			}
			""";

		string generated = $$"""
			{{AutoGenerated.Header}}
			namespace Namespace;

			partial class Class
			{
				{{AutoGenerated.GeneratedCodeAttribute}}
				public static string? GetName(global::System.DateTimeKind value)
				{
					return value switch
					{
						global::System.DateTimeKind.Unspecified => nameof(global::System.DateTimeKind.Unspecified),
						global::System.DateTimeKind.Utc => nameof(global::System.DateTimeKind.Utc),
						global::System.DateTimeKind.Local => nameof(global::System.DateTimeKind.Local),
						_ => null,
					};
				}
			}

			""";

		await Verifier.VerifyAsync(code, ("Namespace.Class.GetName.g.cs", generated));
	}

	[Fact]
	public async Task Execute_GlobalNamespace_AddSource()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			[GeneratedEnumGetNameAttribute<DateTimeKind>]
			public static partial class Class
			{
			}
			""";

		string generated = $$"""
			{{AutoGenerated.Header}}
			partial class Class
			{
				{{AutoGenerated.GeneratedCodeAttribute}}
				public static string? GetName(global::System.DateTimeKind value)
				{
					return value switch
					{
						global::System.DateTimeKind.Unspecified => nameof(global::System.DateTimeKind.Unspecified),
						global::System.DateTimeKind.Utc => nameof(global::System.DateTimeKind.Utc),
						global::System.DateTimeKind.Local => nameof(global::System.DateTimeKind.Local),
						_ => null,
					};
				}
			}

			""";

		await Verifier.VerifyAsync(code, ("Class.GetName.g.cs", generated));
	}

	[Fact]
	public async Task Execute_ErrorType_NoEmit()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumGetNameAttribute<{|#0:Error|}>]
			[GeneratedEnumGetNameAttribute<{|#1:240|}>]
			[{|#2:GeneratedEnumGetNameAttribute<>|}]
			[GeneratedEnumGetNameAttribute<{|#3:]|}
			public static partial class Class
			{
			}
			""";

		DiagnosticResult[] diagnostics = [
			Diagnostic.CS0246(0, "Error"),
			Diagnostic.CS1031(1),
			Diagnostic.CS7003(2),
			Diagnostic.CS1003(3, '>'),
			Diagnostic.CS1031(3),
		];

		await Verifier.VerifyAsync(code, diagnostics);
	}

	[Fact]
	public async Task Execute_IncludeErrors_AddSource()
	{
		string code = """
			using System;
			using FlashOWare.Generators;

			namespace Namespace;

			[GeneratedEnumGetNameAttribute<DateTimeKind>]
			[GeneratedEnumGetNameAttribute<{|#0:Error|}>]
			public static partial class Class
			{
			}

			[GeneratedEnumGetNameAttribute<DateTimeKind, DateTimeKind>]
			[GeneratedEnumGetNameAttribute<?>]
			[GeneratedEnumGetNameAttribute>]
			[GeneratedEnumGetNameAttribute]
			public static partial class Class
			{
			}
			""";

		DiagnosticResult diagnostic = Diagnostic.CS0246(0, "Error");

		string generated = $$"""
			{{AutoGenerated.Header}}
			namespace Namespace;

			partial class Class
			{
				{{AutoGenerated.GeneratedCodeAttribute}}
				public static string? GetName(global::System.DateTimeKind value)
				{
					return value switch
					{
						global::System.DateTimeKind.Unspecified => nameof(global::System.DateTimeKind.Unspecified),
						global::System.DateTimeKind.Utc => nameof(global::System.DateTimeKind.Utc),
						global::System.DateTimeKind.Local => nameof(global::System.DateTimeKind.Local),
						_ => null,
					};
				}
			}

			""";

		await Verifier.VerifyAsync(code, diagnostic, ("Namespace.Class.GetName.g.cs", generated));
	}
}
