namespace FlashOWare.Tests.Text;

internal static class AutoGenerated
{
	public static string Header { get; } = """
		// <auto-generated/>
		#nullable enable

		""";

	public static string GeneratedCodeAttribute { get; } = """
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FlashOWare.Generators", "1.0.0.0")]
		""";

	public static string InterceptsLocationAttribute { get; } = $$"""
		namespace System.Runtime.CompilerServices
		{
			{{GeneratedCodeAttribute}}
			[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
			file sealed class InterceptsLocationAttribute : global::System.Attribute
			{
				public InterceptsLocationAttribute(string filePath, int line, int character)
				{
				}
			}
		}
		""";
}
